// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_screenHome
void ui_screenHome_screen_init(void);
lv_obj_t *ui_screenHome;
lv_obj_t *ui_ImageWaterTank;
lv_obj_t *ui_panelPH;
lv_obj_t *ui_LabelPHValue;
lv_obj_t *ui_phValue;
lv_obj_t *ui_panelEC;
lv_obj_t *ui_LabelECValue;
lv_obj_t *ui_ecValue;
lv_obj_t *ui_ecValue1;
lv_obj_t *ui_panelSensor;
lv_obj_t *ui_LabelTemp;
lv_obj_t *ui_LabelHumidity;
lv_obj_t *ui_temp;
lv_obj_t *ui_temp1;
lv_obj_t *ui_humidity;
lv_obj_t *ui_humidity1;
void ui_event_ButtonControlling1( lv_event_t * e);
lv_obj_t *ui_ButtonControlling1;
lv_obj_t *ui_LabelControlling1;
void ui_event_ButtonNutrient1( lv_event_t * e);
lv_obj_t *ui_ButtonNutrient1;
lv_obj_t *ui_LabelNutrient1;
lv_obj_t *ui_ButtonHome1;
lv_obj_t *ui_LabelHome1;


// SCREEN: ui_screenControlling
void ui_screenControlling_screen_init(void);
lv_obj_t *ui_screenControlling;
lv_obj_t *ui_ButtonControlling2;
lv_obj_t *ui_LabelControlling2;
void ui_event_ButtonNutrient2( lv_event_t * e);
lv_obj_t *ui_ButtonNutrient2;
lv_obj_t *ui_LabelNutrient2;
void ui_event_ButtonHome2( lv_event_t * e);
lv_obj_t *ui_ButtonHome2;
lv_obj_t *ui_LabelHome2;
lv_obj_t *ui_PanelPompa1;
lv_obj_t *ui_LabelPompa1;
void ui_event_ButtonONOFF1( lv_event_t * e);
lv_obj_t *ui_ButtonONOFF1;
lv_obj_t *ui_LabelON1;
lv_obj_t *ui_LabelOFF1;
lv_obj_t *ui_LabelStateOFFPompa1;
lv_obj_t *ui_LabelStateONPompa1;
lv_obj_t *ui_PanelPompa2;
lv_obj_t *ui_LabelPompa2;
void ui_event_ButtonONOFF2( lv_event_t * e);
lv_obj_t *ui_ButtonONOFF2;
lv_obj_t *ui_LabelON2;
lv_obj_t *ui_LabelOFF2;
lv_obj_t *ui_LabelStateOFFPompa2;
lv_obj_t *ui_LabelStateONPompa2;
lv_obj_t *ui_PanelPompa3;
lv_obj_t *ui_LabelPompa3;
void ui_event_ButtonONOFF3( lv_event_t * e);
lv_obj_t *ui_ButtonONOFF3;
lv_obj_t *ui_LabelON3;
lv_obj_t *ui_LabelOFF3;
lv_obj_t *ui_LabelStateOFFPompa3;
lv_obj_t *ui_LabelStateONPompa3;
lv_obj_t *ui_PanelExh;
lv_obj_t *ui_LabelExh;
void ui_event_ButtonONOFF4( lv_event_t * e);
lv_obj_t *ui_ButtonONOFF4;
lv_obj_t *ui_LabelON4;
lv_obj_t *ui_LabelOFF4;
lv_obj_t *ui_LabelStateOFFExh;
lv_obj_t *ui_LabelStateONExh;


// SCREEN: ui_screenNutrient
void ui_screenNutrient_screen_init(void);
lv_obj_t *ui_screenNutrient;
void ui_event_ButtonControlling3( lv_event_t * e);
lv_obj_t *ui_ButtonControlling3;
lv_obj_t *ui_LabelControlling3;
lv_obj_t *ui_ButtonNutrient3;
lv_obj_t *ui_LabelNutrient3;
void ui_event_ButtonHome3( lv_event_t * e);
lv_obj_t *ui_ButtonHome3;
lv_obj_t *ui_LabelHome3;
void ui_event_TextAreaECTarget( lv_event_t * e);
lv_obj_t *ui_TextAreaECTarget;
lv_obj_t *ui_LabelECTarget;
lv_obj_t *ui_LabelMixTime;
void ui_event_TextAreaMixTime( lv_event_t * e);
lv_obj_t *ui_TextAreaMixTime;
lv_obj_t *ui_LabelDoseA;
lv_obj_t *ui_LabelDoseB;
lv_obj_t *ui_doseA;
lv_obj_t *ui_doseB;
void ui_event_ButtonStart( lv_event_t * e);
lv_obj_t *ui_ButtonStart;
lv_obj_t *ui_LabelButtonStart;
lv_obj_t *ui_Keyboard1;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ButtonControlling1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenControlling, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenControlling_screen_init);
}
}
void ui_event_ButtonNutrient1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenNutrient, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenNutrient_screen_init);
}
}
void ui_event_ButtonNutrient2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenNutrient, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenNutrient_screen_init);
}
}
void ui_event_ButtonHome2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenHome_screen_init);
}
}
void ui_event_ButtonONOFF1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_ButtonONOFF1, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_LabelStateOFFPompa1, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_LabelStateONPompa1, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_LabelOFF1, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_LabelON1, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      OnOffPompa1( e );
}
}
void ui_event_ButtonONOFF2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_LabelON2, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_LabelOFF2, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_LabelStateOFFPompa2, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_LabelStateONPompa2, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_ButtonONOFF2, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      OnOffPompa2( e );
}
}
void ui_event_ButtonONOFF3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_LabelON3, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_LabelOFF3, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_LabelStateOFFPompa3, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_LabelStateONPompa3, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_ButtonONOFF3, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      OnOffPompa2( e );
}
}
void ui_event_ButtonONOFF4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_LabelON4, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_LabelOFF4, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_LabelStateOFFExh, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_LabelStateONExh, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_ButtonONOFF4, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      OnOffPompa2( e );
}
}
void ui_event_ButtonControlling3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenControlling, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenControlling_screen_init);
}
}
void ui_event_ButtonHome3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenHome_screen_init);
}
}
void ui_event_TextAreaECTarget( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      calculateAB( e );
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_TextAreaECTarget);
}
}
void ui_event_TextAreaMixTime( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      calculateAB( e );
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_TextAreaMixTime);
}
}
void ui_event_ButtonStart( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      startManualNutrient( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_screenHome_screen_init();
ui_screenControlling_screen_init();
ui_screenNutrient_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_screenHome);
}
