// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_screenHome
void ui_screenHome_screen_init(void);
extern lv_obj_t *ui_screenHome;
extern lv_obj_t *ui_panelPH;
extern lv_obj_t *ui_LabelPHValue;
extern lv_obj_t *ui_phValue;
extern lv_obj_t *ui_panelEC;
extern lv_obj_t *ui_LabelECValue;
extern lv_obj_t *ui_ecValue;
extern lv_obj_t *ui_ecValue1;
extern lv_obj_t *ui_panelSensor;
extern lv_obj_t *ui_LabelTemp;
extern lv_obj_t *ui_LabelHumidity;
extern lv_obj_t *ui_labelSoil;
extern lv_obj_t *ui_temp;
extern lv_obj_t *ui_temp1;
extern lv_obj_t *ui_humidity;
extern lv_obj_t *ui_humidity1;
extern lv_obj_t *ui_Soil_Moisture;
extern lv_obj_t *ui_Soil_Moisture1;
void ui_event_ButtonControlling1( lv_event_t * e);
extern lv_obj_t *ui_ButtonControlling1;
extern lv_obj_t *ui_LabelControlling1;
void ui_event_ButtonNutrient1( lv_event_t * e);
extern lv_obj_t *ui_ButtonNutrient1;
extern lv_obj_t *ui_LabelNutrient1;
extern lv_obj_t *ui_ButtonHome1;
extern lv_obj_t *ui_LabelHome1;
void ui_event_ButtonWifi( lv_event_t * e);
extern lv_obj_t *ui_ButtonWifi;
extern lv_obj_t *ui_LabelWifi1;
// SCREEN: ui_screenControlling
void ui_screenControlling_screen_init(void);
extern lv_obj_t *ui_screenControlling;
extern lv_obj_t *ui_ButtonControlling2;
extern lv_obj_t *ui_LabelControlling2;
void ui_event_ButtonNutrient2( lv_event_t * e);
extern lv_obj_t *ui_ButtonNutrient2;
extern lv_obj_t *ui_LabelNutrient2;
void ui_event_ButtonHome2( lv_event_t * e);
extern lv_obj_t *ui_ButtonHome2;
extern lv_obj_t *ui_LabelHome2;
extern lv_obj_t *ui_PanelPompa1;
extern lv_obj_t *ui_LabelPompa1;
void ui_event_ButtonONOFF1( lv_event_t * e);
extern lv_obj_t *ui_ButtonONOFF1;
extern lv_obj_t *ui_LabelON1;
extern lv_obj_t *ui_LabelOFF1;
extern lv_obj_t *ui_LabelStateOFFPompa1;
extern lv_obj_t *ui_LabelStateONPompa1;
extern lv_obj_t *ui_PanelPompa2;
extern lv_obj_t *ui_LabelPompa2;
void ui_event_ButtonONOFF2( lv_event_t * e);
extern lv_obj_t *ui_ButtonONOFF2;
extern lv_obj_t *ui_LabelON2;
extern lv_obj_t *ui_LabelOFF2;
extern lv_obj_t *ui_LabelStateOFFPompa2;
extern lv_obj_t *ui_LabelStateONPompa2;
extern lv_obj_t *ui_PanelPompa3;
extern lv_obj_t *ui_LabelPompa3;
void ui_event_ButtonONOFF3( lv_event_t * e);
extern lv_obj_t *ui_ButtonONOFF3;
extern lv_obj_t *ui_LabelON3;
extern lv_obj_t *ui_LabelOFF3;
extern lv_obj_t *ui_LabelStateOFFPompa3;
extern lv_obj_t *ui_LabelStateONPompa3;
extern lv_obj_t *ui_PanelExh;
extern lv_obj_t *ui_LabelExh;
void ui_event_ButtonONOFF4( lv_event_t * e);
extern lv_obj_t *ui_ButtonONOFF4;
extern lv_obj_t *ui_LabelON4;
extern lv_obj_t *ui_LabelOFF4;
extern lv_obj_t *ui_LabelStateOFFExh;
extern lv_obj_t *ui_LabelStateONExh;
// SCREEN: ui_screenNutrient
void ui_screenNutrient_screen_init(void);
extern lv_obj_t *ui_screenNutrient;
void ui_event_ButtonControlling3( lv_event_t * e);
extern lv_obj_t *ui_ButtonControlling3;
extern lv_obj_t *ui_LabelControlling3;
extern lv_obj_t *ui_ButtonNutrient3;
extern lv_obj_t *ui_LabelNutrient3;
void ui_event_ButtonHome3( lv_event_t * e);
extern lv_obj_t *ui_ButtonHome3;
extern lv_obj_t *ui_LabelHome3;
void ui_event_TextAreaECTarget( lv_event_t * e);
extern lv_obj_t *ui_TextAreaECTarget;
extern lv_obj_t *ui_LabelECTarget;
extern lv_obj_t *ui_LabelMixTime;
void ui_event_TextAreaMixTime( lv_event_t * e);
extern lv_obj_t *ui_TextAreaMixTime;
extern lv_obj_t *ui_LabelDoseA;
extern lv_obj_t *ui_LabelDoseB;
extern lv_obj_t *ui_doseA;
extern lv_obj_t *ui_doseB;
void ui_event_ButtonStart( lv_event_t * e);
extern lv_obj_t *ui_ButtonStart;
extern lv_obj_t *ui_LabelButtonStart;
extern lv_obj_t *ui_Keyboard1;
extern lv_obj_t *ui_LabelTime;
extern lv_obj_t *ui____initial_actions0;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
