// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_LABEL7_H
#define _UI_COMP_LABEL7_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Label7
#define UI_COMP_LABEL7_LABEL7 0
#define _UI_COMP_LABEL7_NUM 1
lv_obj_t *ui_Label7_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
