// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


// COMPONENT Label7

lv_obj_t *ui_Label7_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Label7;
cui_Label7 = lv_label_create(comp_parent);
lv_obj_set_width( cui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_Label7, 3 );
lv_obj_set_y( cui_Label7, lv_pct(-31) );
lv_obj_set_align( cui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label7,"30 ");

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LABEL7_NUM);
children[UI_COMP_LABEL7_LABEL7] = cui_Label7;
lv_obj_add_event_cb(cui_Label7, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Label7, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Label7_create_hook(cui_Label7);
return cui_Label7; 
}

