// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void connectWifi(lv_event_t * e);
void OnOffPompa1(lv_event_t * e);
void OnOffPompa2(lv_event_t * e);
void OnOffPompa3(lv_event_t * e);
void OnOffExh(lv_event_t * e);
void calculateAB(lv_event_t * e);
void startManualNutrient(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
