// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

// #include "ui.h"

// void OnOffPompa1(lv_event_t * e)
// {
// 	// Your code here
// }

// void OnOffPompa2(lv_event_t * e)
// {
// 	// Your code here
// }

// void calculateAB(lv_event_t * e)
// {
// 	// Your code here
// }

// void startManualNutrient(lv_event_t * e)
// {
// 	// Your code here
// }
