// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_screenControlling_screen_init(void)
{
ui_screenControlling = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenControlling, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screenControlling, lv_color_hex(0x17926D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screenControlling, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_screenControlling);
lv_obj_set_width( ui_Panel4, 730);
lv_obj_set_height( ui_Panel4, 370);
lv_obj_set_x( ui_Panel4, 0 );
lv_obj_set_y( ui_Panel4, 15 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x17926D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonControlling2 = lv_btn_create(ui_screenControlling);
lv_obj_set_width( ui_ButtonControlling2, 100);
lv_obj_set_height( ui_ButtonControlling2, 60);
lv_obj_set_x( ui_ButtonControlling2, -160 );
lv_obj_set_y( ui_ButtonControlling2, -160 );
lv_obj_set_align( ui_ButtonControlling2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonControlling2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonControlling2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonControlling2, lv_color_hex(0x0D634A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonControlling2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonControlling2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonControlling2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelControlling2 = lv_label_create(ui_ButtonControlling2);
lv_obj_set_width( ui_LabelControlling2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelControlling2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelControlling2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelControlling2,"Controlling");

ui_ButtonNutrient2 = lv_btn_create(ui_screenControlling);
lv_obj_set_width( ui_ButtonNutrient2, 100);
lv_obj_set_height( ui_ButtonNutrient2, 60);
lv_obj_set_x( ui_ButtonNutrient2, -35 );
lv_obj_set_y( ui_ButtonNutrient2, -160 );
lv_obj_set_align( ui_ButtonNutrient2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonNutrient2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonNutrient2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonNutrient2, lv_color_hex(0x0F8161), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonNutrient2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonNutrient2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonNutrient2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelNutrient2 = lv_label_create(ui_ButtonNutrient2);
lv_obj_set_width( ui_LabelNutrient2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelNutrient2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelNutrient2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelNutrient2,"Nutrient");

ui_ButtonHome2 = lv_btn_create(ui_screenControlling);
lv_obj_set_width( ui_ButtonHome2, 100);
lv_obj_set_height( ui_ButtonHome2, 60);
lv_obj_set_x( ui_ButtonHome2, -285 );
lv_obj_set_y( ui_ButtonHome2, -160 );
lv_obj_set_align( ui_ButtonHome2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonHome2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonHome2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonHome2, lv_color_hex(0x0F8161), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonHome2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonHome2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonHome2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHome2 = lv_label_create(ui_ButtonHome2);
lv_obj_set_width( ui_LabelHome2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHome2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelHome2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHome2,"Home");

ui_PanelPompa1 = lv_obj_create(ui_screenControlling);
lv_obj_set_width( ui_PanelPompa1, 150);
lv_obj_set_height( ui_PanelPompa1, 150);
lv_obj_set_x( ui_PanelPompa1, -260 );
lv_obj_set_y( ui_PanelPompa1, -30 );
lv_obj_set_align( ui_PanelPompa1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPompa1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPompa1 = lv_label_create(ui_PanelPompa1);
lv_obj_set_width( ui_LabelPompa1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPompa1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPompa1, 0 );
lv_obj_set_y( ui_LabelPompa1, -50 );
lv_obj_set_align( ui_LabelPompa1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPompa1,"Watering\nPump");
lv_obj_set_style_text_align(ui_LabelPompa1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonONOFF1 = lv_btn_create(ui_PanelPompa1);
lv_obj_set_width( ui_ButtonONOFF1, 120);
lv_obj_set_height( ui_ButtonONOFF1, 60);
lv_obj_set_x( ui_ButtonONOFF1, -1 );
lv_obj_set_y( ui_ButtonONOFF1, 25 );
lv_obj_set_align( ui_ButtonONOFF1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonONOFF1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonONOFF1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonONOFF1, lv_color_hex(0x0F8161), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonONOFF1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonONOFF1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonONOFF1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonONOFF1, lv_color_hex(0xE20000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ButtonONOFF1, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_color(ui_ButtonONOFF1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_ButtonONOFF1, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelON1 = lv_label_create(ui_ButtonONOFF1);
lv_obj_set_width( ui_LabelON1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelON1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelON1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelON1,"ON");

ui_LabelStateOFFPompa1 = lv_label_create(ui_PanelPompa1);
lv_obj_set_width( ui_LabelStateOFFPompa1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStateOFFPompa1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStateOFFPompa1, 0 );
lv_obj_set_y( ui_LabelStateOFFPompa1, -21 );
lv_obj_set_align( ui_LabelStateOFFPompa1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStateOFFPompa1,"State: OFF");
lv_obj_set_style_text_color(ui_LabelStateOFFPompa1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStateOFFPompa1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPompa2 = lv_obj_create(ui_screenControlling);
lv_obj_set_width( ui_PanelPompa2, 150);
lv_obj_set_height( ui_PanelPompa2, 150);
lv_obj_set_x( ui_PanelPompa2, -85 );
lv_obj_set_y( ui_PanelPompa2, -30 );
lv_obj_set_align( ui_PanelPompa2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPompa2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPompa2 = lv_label_create(ui_PanelPompa2);
lv_obj_set_width( ui_LabelPompa2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPompa2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPompa2, 0 );
lv_obj_set_y( ui_LabelPompa2, -50 );
lv_obj_set_align( ui_LabelPompa2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPompa2,"Mixing\nPump");
lv_obj_set_style_text_align(ui_LabelPompa2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonONOFF2 = lv_btn_create(ui_PanelPompa2);
lv_obj_set_width( ui_ButtonONOFF2, 120);
lv_obj_set_height( ui_ButtonONOFF2, 60);
lv_obj_set_x( ui_ButtonONOFF2, -1 );
lv_obj_set_y( ui_ButtonONOFF2, 25 );
lv_obj_set_align( ui_ButtonONOFF2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonONOFF2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonONOFF2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonONOFF2, lv_color_hex(0x0F8161), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonONOFF2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonONOFF2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonONOFF2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonONOFF2, lv_color_hex(0xE20000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ButtonONOFF2, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_color(ui_ButtonONOFF2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_ButtonONOFF2, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelON2 = lv_label_create(ui_ButtonONOFF2);
lv_obj_set_width( ui_LabelON2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelON2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelON2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelON2,"ON");

ui_LabelStateOFFPompa2 = lv_label_create(ui_PanelPompa2);
lv_obj_set_width( ui_LabelStateOFFPompa2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStateOFFPompa2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStateOFFPompa2, 0 );
lv_obj_set_y( ui_LabelStateOFFPompa2, -21 );
lv_obj_set_align( ui_LabelStateOFFPompa2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStateOFFPompa2,"State: OFF");
lv_obj_set_style_text_color(ui_LabelStateOFFPompa2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStateOFFPompa2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPompa3 = lv_obj_create(ui_screenControlling);
lv_obj_set_width( ui_PanelPompa3, 150);
lv_obj_set_height( ui_PanelPompa3, 150);
lv_obj_set_x( ui_PanelPompa3, 85 );
lv_obj_set_y( ui_PanelPompa3, -30 );
lv_obj_set_align( ui_PanelPompa3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPompa3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPompa3 = lv_label_create(ui_PanelPompa3);
lv_obj_set_width( ui_LabelPompa3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPompa3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPompa3, 0 );
lv_obj_set_y( ui_LabelPompa3, -50 );
lv_obj_set_align( ui_LabelPompa3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPompa3,"Dosing\nPump");
lv_obj_set_style_text_align(ui_LabelPompa3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonONOFF3 = lv_btn_create(ui_PanelPompa3);
lv_obj_set_width( ui_ButtonONOFF3, 120);
lv_obj_set_height( ui_ButtonONOFF3, 60);
lv_obj_set_x( ui_ButtonONOFF3, -1 );
lv_obj_set_y( ui_ButtonONOFF3, 25 );
lv_obj_set_align( ui_ButtonONOFF3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonONOFF3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonONOFF3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonONOFF3, lv_color_hex(0x0F8161), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonONOFF3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonONOFF3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonONOFF3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonONOFF3, lv_color_hex(0xE20000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ButtonONOFF3, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_color(ui_ButtonONOFF3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_ButtonONOFF3, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelON3 = lv_label_create(ui_ButtonONOFF3);
lv_obj_set_width( ui_LabelON3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelON3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelON3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelON3,"ON");

ui_LabelStateOFFPompa3 = lv_label_create(ui_PanelPompa3);
lv_obj_set_width( ui_LabelStateOFFPompa3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStateOFFPompa3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStateOFFPompa3, 0 );
lv_obj_set_y( ui_LabelStateOFFPompa3, -21 );
lv_obj_set_align( ui_LabelStateOFFPompa3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStateOFFPompa3,"State: OFF");
lv_obj_set_style_text_color(ui_LabelStateOFFPompa3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStateOFFPompa3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelExh = lv_obj_create(ui_screenControlling);
lv_obj_set_width( ui_PanelExh, 150);
lv_obj_set_height( ui_PanelExh, 150);
lv_obj_set_x( ui_PanelExh, 260 );
lv_obj_set_y( ui_PanelExh, -30 );
lv_obj_set_align( ui_PanelExh, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelExh, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelExh = lv_label_create(ui_PanelExh);
lv_obj_set_width( ui_LabelExh, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelExh, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelExh, 0 );
lv_obj_set_y( ui_LabelExh, -50 );
lv_obj_set_align( ui_LabelExh, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelExh,"Exhaust\nFan");
lv_obj_set_style_text_align(ui_LabelExh, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonONOFF4 = lv_btn_create(ui_PanelExh);
lv_obj_set_width( ui_ButtonONOFF4, 120);
lv_obj_set_height( ui_ButtonONOFF4, 60);
lv_obj_set_x( ui_ButtonONOFF4, -1 );
lv_obj_set_y( ui_ButtonONOFF4, 25 );
lv_obj_set_align( ui_ButtonONOFF4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonONOFF4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonONOFF4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonONOFF4, lv_color_hex(0x0F8161), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonONOFF4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonONOFF4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonONOFF4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonONOFF4, lv_color_hex(0xE20000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ButtonONOFF4, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_color(ui_ButtonONOFF4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_ButtonONOFF4, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelON4 = lv_label_create(ui_ButtonONOFF4);
lv_obj_set_width( ui_LabelON4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelON4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelON4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelON4,"ON");

ui_LabelStateOFFExh = lv_label_create(ui_PanelExh);
lv_obj_set_width( ui_LabelStateOFFExh, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStateOFFExh, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStateOFFExh, 0 );
lv_obj_set_y( ui_LabelStateOFFExh, -21 );
lv_obj_set_align( ui_LabelStateOFFExh, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStateOFFExh,"State: OFF");
lv_obj_set_style_text_color(ui_LabelStateOFFExh, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStateOFFExh, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ButtonNutrient2, ui_event_ButtonNutrient2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonHome2, ui_event_ButtonHome2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonONOFF1, ui_event_ButtonONOFF1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonONOFF2, ui_event_ButtonONOFF2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonONOFF3, ui_event_ButtonONOFF3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonONOFF4, ui_event_ButtonONOFF4, LV_EVENT_ALL, NULL);

}
