// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_screenNutrient_screen_init(void)
{
ui_screenNutrient = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenNutrient, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screenNutrient, lv_color_hex(0x4A9C79), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screenNutrient, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonControlling3 = lv_btn_create(ui_screenNutrient);
lv_obj_set_width( ui_ButtonControlling3, 100);
lv_obj_set_height( ui_ButtonControlling3, 60);
lv_obj_set_x( ui_ButtonControlling3, -160 );
lv_obj_set_y( ui_ButtonControlling3, -160 );
lv_obj_set_align( ui_ButtonControlling3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonControlling3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonControlling3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonControlling3, lv_color_hex(0x0F8161), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonControlling3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonControlling3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonControlling3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelControlling3 = lv_label_create(ui_ButtonControlling3);
lv_obj_set_width( ui_LabelControlling3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelControlling3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelControlling3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelControlling3,"Controlling");

ui_ButtonNutrient3 = lv_btn_create(ui_screenNutrient);
lv_obj_set_width( ui_ButtonNutrient3, 100);
lv_obj_set_height( ui_ButtonNutrient3, 60);
lv_obj_set_x( ui_ButtonNutrient3, -35 );
lv_obj_set_y( ui_ButtonNutrient3, -160 );
lv_obj_set_align( ui_ButtonNutrient3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonNutrient3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonNutrient3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonNutrient3, lv_color_hex(0x426A5E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonNutrient3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonNutrient3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonNutrient3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelNutrient3 = lv_label_create(ui_ButtonNutrient3);
lv_obj_set_width( ui_LabelNutrient3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelNutrient3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelNutrient3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelNutrient3,"Nutrient");

ui_ButtonHome3 = lv_btn_create(ui_screenNutrient);
lv_obj_set_width( ui_ButtonHome3, 100);
lv_obj_set_height( ui_ButtonHome3, 60);
lv_obj_set_x( ui_ButtonHome3, -285 );
lv_obj_set_y( ui_ButtonHome3, -160 );
lv_obj_set_align( ui_ButtonHome3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonHome3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonHome3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonHome3, lv_color_hex(0x0F8161), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonHome3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonHome3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonHome3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHome3 = lv_label_create(ui_ButtonHome3);
lv_obj_set_width( ui_LabelHome3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHome3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelHome3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHome3,"Home");

ui_TextAreaECTarget = lv_textarea_create(ui_screenNutrient);
lv_obj_set_width( ui_TextAreaECTarget, 140);
lv_obj_set_height( ui_TextAreaECTarget, 39);
lv_obj_set_x( ui_TextAreaECTarget, -90 );
lv_obj_set_y( ui_TextAreaECTarget, -80 );
lv_obj_set_align( ui_TextAreaECTarget, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextAreaECTarget,"EC Target");



ui_LabelECTarget = lv_label_create(ui_screenNutrient);
lv_obj_set_width( ui_LabelECTarget, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelECTarget, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelECTarget, -260 );
lv_obj_set_y( ui_LabelECTarget, -80 );
lv_obj_set_align( ui_LabelECTarget, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelECTarget,"EC Target (uS/cm)   : ");

ui_LabelMixTime = lv_label_create(ui_screenNutrient);
lv_obj_set_width( ui_LabelMixTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMixTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMixTime, -260 );
lv_obj_set_y( ui_LabelMixTime, -20 );
lv_obj_set_align( ui_LabelMixTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMixTime,"Mix Time (detik)      : ");

ui_TextAreaMixTime = lv_textarea_create(ui_screenNutrient);
lv_obj_set_width( ui_TextAreaMixTime, 140);
lv_obj_set_height( ui_TextAreaMixTime, 39);
lv_obj_set_x( ui_TextAreaMixTime, -90 );
lv_obj_set_y( ui_TextAreaMixTime, -20 );
lv_obj_set_align( ui_TextAreaMixTime, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextAreaMixTime,"Mix Time");



ui_LabelDoseA = lv_label_create(ui_screenNutrient);
lv_obj_set_width( ui_LabelDoseA, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelDoseA, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelDoseA, -260 );
lv_obj_set_y( ui_LabelDoseA, 27 );
lv_obj_set_align( ui_LabelDoseA, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelDoseA,"Est Dose A  (ml)       : ");

ui_LabelDoseB = lv_label_create(ui_screenNutrient);
lv_obj_set_width( ui_LabelDoseB, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelDoseB, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelDoseB, -260 );
lv_obj_set_y( ui_LabelDoseB, 72 );
lv_obj_set_align( ui_LabelDoseB, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelDoseB,"Est Dose B (ml)       : ");

ui_doseA = lv_label_create(ui_screenNutrient);
lv_obj_set_width( ui_doseA, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_doseA, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_doseA, 240 );
lv_obj_set_y( ui_doseA, 260 );
lv_label_set_text(ui_doseA,"0");
lv_obj_set_style_text_align(ui_doseA, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_doseB = lv_label_create(ui_screenNutrient);
lv_obj_set_width( ui_doseB, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_doseB, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_doseB, 240 );
lv_obj_set_y( ui_doseB, 306 );
lv_label_set_text(ui_doseB,"0");
lv_obj_set_style_text_align(ui_doseB, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonStart = lv_btn_create(ui_screenNutrient);
lv_obj_set_width( ui_ButtonStart, 100);
lv_obj_set_height( ui_ButtonStart, 60);
lv_obj_set_x( ui_ButtonStart, -166 );
lv_obj_set_y( ui_ButtonStart, 138 );
lv_obj_set_align( ui_ButtonStart, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonStart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonStart, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonStart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonStart, lv_color_hex(0xF55D5D), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ButtonStart, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelButtonStart = lv_label_create(ui_ButtonStart);
lv_obj_set_width( ui_LabelButtonStart, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelButtonStart, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelButtonStart, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelButtonStart,"Start");

ui_Keyboard1 = lv_keyboard_create(ui_screenNutrient);
lv_keyboard_set_mode(ui_Keyboard1,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_Keyboard1, 368);
lv_obj_set_height( ui_Keyboard1, 284);
lv_obj_set_x( ui_Keyboard1, 177 );
lv_obj_set_y( ui_Keyboard1, 43 );
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Keyboard1, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelTime = lv_label_create(ui_screenNutrient);
lv_obj_set_width( ui_LabelTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTime, 283 );
lv_obj_set_y( ui_LabelTime, -160 );
lv_obj_set_align( ui_LabelTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTime,"Time: 0");
lv_obj_set_style_text_font(ui_LabelTime, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ButtonControlling3, ui_event_ButtonControlling3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonHome3, ui_event_ButtonHome3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaECTarget, ui_event_TextAreaECTarget, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaMixTime, ui_event_TextAreaMixTime, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonStart, ui_event_ButtonStart, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_Keyboard1,ui_TextAreaECTarget);

}
