// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_screenNutrient1_screen_init(void)
{
ui_screenNutrient1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenNutrient1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screenNutrient1, lv_color_hex(0x7EB89F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screenNutrient1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonControlling4 = lv_btn_create(ui_screenNutrient1);
lv_obj_set_width( ui_ButtonControlling4, 100);
lv_obj_set_height( ui_ButtonControlling4, 40);
lv_obj_set_x( ui_ButtonControlling4, 160 );
lv_obj_set_y( ui_ButtonControlling4, -160 );
lv_obj_set_align( ui_ButtonControlling4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonControlling4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonControlling4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonControlling4, lv_color_hex(0x0F8161), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonControlling4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonControlling4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonControlling4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelControlling4 = lv_label_create(ui_ButtonControlling4);
lv_obj_set_width( ui_LabelControlling4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelControlling4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelControlling4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelControlling4,"Controlling");

ui_ButtonNutrient4 = lv_btn_create(ui_screenNutrient1);
lv_obj_set_width( ui_ButtonNutrient4, 100);
lv_obj_set_height( ui_ButtonNutrient4, 40);
lv_obj_set_x( ui_ButtonNutrient4, 285 );
lv_obj_set_y( ui_ButtonNutrient4, -160 );
lv_obj_set_align( ui_ButtonNutrient4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonNutrient4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonNutrient4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonNutrient4, lv_color_hex(0x426A5E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonNutrient4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonNutrient4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonNutrient4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LlabelNutrient4 = lv_label_create(ui_ButtonNutrient4);
lv_obj_set_width( ui_LlabelNutrient4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LlabelNutrient4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LlabelNutrient4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LlabelNutrient4,"Nutrient");

ui_ButtonHome4 = lv_btn_create(ui_screenNutrient1);
lv_obj_set_width( ui_ButtonHome4, 100);
lv_obj_set_height( ui_ButtonHome4, 40);
lv_obj_set_x( ui_ButtonHome4, 35 );
lv_obj_set_y( ui_ButtonHome4, -160 );
lv_obj_set_align( ui_ButtonHome4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonHome4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonHome4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonHome4, lv_color_hex(0x0F8161), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonHome4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonHome4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonHome4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHome4 = lv_label_create(ui_ButtonHome4);
lv_obj_set_width( ui_LabelHome4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHome4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelHome4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHome4,"Home");

ui_LabelMixTime2 = lv_label_create(ui_screenNutrient1);
lv_obj_set_width( ui_LabelMixTime2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMixTime2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMixTime2, -281 );
lv_obj_set_y( ui_LabelMixTime2, -82 );
lv_obj_set_align( ui_LabelMixTime2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMixTime2,"Mix Time            : ");

ui_TextAreaMixTime2 = lv_textarea_create(ui_screenNutrient1);
lv_obj_set_width( ui_TextAreaMixTime2, 140);
lv_obj_set_height( ui_TextAreaMixTime2, 39);
lv_obj_set_x( ui_TextAreaMixTime2, -140 );
lv_obj_set_y( ui_TextAreaMixTime2, -81 );
lv_obj_set_align( ui_TextAreaMixTime2, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextAreaMixTime2,"Mix Time");



ui_LabelDoseA2 = lv_label_create(ui_screenNutrient1);
lv_obj_set_width( ui_LabelDoseA2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelDoseA2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelDoseA2, -280 );
lv_obj_set_y( ui_LabelDoseA2, -26 );
lv_obj_set_align( ui_LabelDoseA2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelDoseA2,"Dose A               : ");

ui_LabelDoseB2 = lv_label_create(ui_screenNutrient1);
lv_obj_set_width( ui_LabelDoseB2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelDoseB2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelDoseB2, -280 );
lv_obj_set_y( ui_LabelDoseB2, 30 );
lv_obj_set_align( ui_LabelDoseB2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelDoseB2,"Dose B               : ");

ui_ButtonStart2 = lv_btn_create(ui_screenNutrient1);
lv_obj_set_width( ui_ButtonStart2, 100);
lv_obj_set_height( ui_ButtonStart2, 50);
lv_obj_set_x( ui_ButtonStart2, -166 );
lv_obj_set_y( ui_ButtonStart2, 120 );
lv_obj_set_align( ui_ButtonStart2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonStart2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonStart2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelButtonStart2 = lv_label_create(ui_ButtonStart2);
lv_obj_set_width( ui_LabelButtonStart2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelButtonStart2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelButtonStart2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelButtonStart2,"Start");

ui_ButtonAuto = lv_btn_create(ui_screenNutrient1);
lv_obj_set_width( ui_ButtonAuto, 100);
lv_obj_set_height( ui_ButtonAuto, 36);
lv_obj_set_x( ui_ButtonAuto, 297 );
lv_obj_set_y( ui_ButtonAuto, 174 );
lv_obj_set_align( ui_ButtonAuto, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonAuto, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonAuto, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonAuto, lv_color_hex(0x0F8161), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonAuto, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonAuto, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonAuto, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelAuto = lv_label_create(ui_ButtonAuto);
lv_obj_set_width( ui_LabelAuto, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelAuto, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelAuto, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelAuto,"Auto");

ui_TextAreaDoseA = lv_textarea_create(ui_screenNutrient1);
lv_obj_set_width( ui_TextAreaDoseA, 140);
lv_obj_set_height( ui_TextAreaDoseA, 39);
lv_obj_set_x( ui_TextAreaDoseA, -140 );
lv_obj_set_y( ui_TextAreaDoseA, -26 );
lv_obj_set_align( ui_TextAreaDoseA, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextAreaDoseA,"Dose A");



ui_TextAreaDoseB = lv_textarea_create(ui_screenNutrient1);
lv_obj_set_width( ui_TextAreaDoseB, 140);
lv_obj_set_height( ui_TextAreaDoseB, 39);
lv_obj_set_x( ui_TextAreaDoseB, -140 );
lv_obj_set_y( ui_TextAreaDoseB, 29 );
lv_obj_set_align( ui_TextAreaDoseB, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextAreaDoseB,"Dose B");



lv_obj_add_event_cb(ui_ButtonControlling4, ui_event_ButtonControlling4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonHome4, ui_event_ButtonHome4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaMixTime2, ui_event_TextAreaMixTime2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonStart2, ui_event_ButtonStart2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonAuto, ui_event_ButtonAuto, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaDoseA, ui_event_TextAreaDoseA, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaDoseB, ui_event_TextAreaDoseB, LV_EVENT_ALL, NULL);

}
