// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_screenControlling_screen_init(void)
{
ui_screenControlling = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenControlling, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screenControlling, lv_color_hex(0x7EB89F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screenControlling, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonControlling2 = lv_btn_create(ui_screenControlling);
lv_obj_set_width( ui_ButtonControlling2, 100);
lv_obj_set_height( ui_ButtonControlling2, 40);
lv_obj_set_x( ui_ButtonControlling2, 160 );
lv_obj_set_y( ui_ButtonControlling2, -160 );
lv_obj_set_align( ui_ButtonControlling2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonControlling2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonControlling2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonControlling2, lv_color_hex(0x426A5E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonControlling2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonControlling2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonControlling2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelControlling2 = lv_label_create(ui_ButtonControlling2);
lv_obj_set_width( ui_LabelControlling2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelControlling2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelControlling2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelControlling2,"Controlling");

ui_ButtonNutrient2 = lv_btn_create(ui_screenControlling);
lv_obj_set_width( ui_ButtonNutrient2, 100);
lv_obj_set_height( ui_ButtonNutrient2, 40);
lv_obj_set_x( ui_ButtonNutrient2, 285 );
lv_obj_set_y( ui_ButtonNutrient2, -160 );
lv_obj_set_align( ui_ButtonNutrient2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonNutrient2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonNutrient2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonNutrient2, lv_color_hex(0x0F8161), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonNutrient2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonNutrient2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonNutrient2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelNutrient2 = lv_label_create(ui_ButtonNutrient2);
lv_obj_set_width( ui_LabelNutrient2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelNutrient2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelNutrient2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelNutrient2,"Nutrient");

ui_ButtonHome2 = lv_btn_create(ui_screenControlling);
lv_obj_set_width( ui_ButtonHome2, 100);
lv_obj_set_height( ui_ButtonHome2, 40);
lv_obj_set_x( ui_ButtonHome2, 35 );
lv_obj_set_y( ui_ButtonHome2, -160 );
lv_obj_set_align( ui_ButtonHome2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonHome2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonHome2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonHome2, lv_color_hex(0x0F8161), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonHome2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonHome2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonHome2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHome2 = lv_label_create(ui_ButtonHome2);
lv_obj_set_width( ui_LabelHome2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHome2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelHome2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHome2,"Home");

ui_PanelPompa1 = lv_obj_create(ui_screenControlling);
lv_obj_set_width( ui_PanelPompa1, 123);
lv_obj_set_height( ui_PanelPompa1, 131);
lv_obj_set_x( ui_PanelPompa1, -280 );
lv_obj_set_y( ui_PanelPompa1, -47 );
lv_obj_set_align( ui_PanelPompa1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPompa1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPompa1 = lv_label_create(ui_PanelPompa1);
lv_obj_set_width( ui_LabelPompa1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPompa1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPompa1, 0 );
lv_obj_set_y( ui_LabelPompa1, -40 );
lv_obj_set_align( ui_LabelPompa1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPompa1,"Watering\nPump");
lv_obj_set_style_text_align(ui_LabelPompa1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonONOFF1 = lv_btn_create(ui_PanelPompa1);
lv_obj_set_width( ui_ButtonONOFF1, 100);
lv_obj_set_height( ui_ButtonONOFF1, 50);
lv_obj_set_x( ui_ButtonONOFF1, 0 );
lv_obj_set_y( ui_ButtonONOFF1, 30 );
lv_obj_set_align( ui_ButtonONOFF1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonONOFF1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonONOFF1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonONOFF1, lv_color_hex(0x0F8161), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonONOFF1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonONOFF1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonONOFF1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonONOFF1, lv_color_hex(0xE20000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ButtonONOFF1, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_color(ui_ButtonONOFF1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_ButtonONOFF1, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelON1 = lv_label_create(ui_ButtonONOFF1);
lv_obj_set_width( ui_LabelON1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelON1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelON1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelON1,"ON");
lv_obj_set_style_text_color(ui_LabelON1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_LabelON1, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelOFF1 = lv_label_create(ui_ButtonONOFF1);
lv_obj_set_width( ui_LabelOFF1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelOFF1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelOFF1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelOFF1,"OFF");
lv_obj_set_style_text_color(ui_LabelOFF1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelOFF1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_LabelOFF1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_LabelOFF1, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelStateOFFPompa1 = lv_label_create(ui_PanelPompa1);
lv_obj_set_width( ui_LabelStateOFFPompa1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStateOFFPompa1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStateOFFPompa1, 0 );
lv_obj_set_y( ui_LabelStateOFFPompa1, -15 );
lv_obj_set_align( ui_LabelStateOFFPompa1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStateOFFPompa1,"State: OFF");
lv_obj_set_style_text_color(ui_LabelStateOFFPompa1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStateOFFPompa1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_LabelStateOFFPompa1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_LabelStateOFFPompa1, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelStateONPompa1 = lv_label_create(ui_PanelPompa1);
lv_obj_set_width( ui_LabelStateONPompa1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStateONPompa1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStateONPompa1, 0 );
lv_obj_set_y( ui_LabelStateONPompa1, -15 );
lv_obj_set_align( ui_LabelStateONPompa1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStateONPompa1,"State: ON");
lv_obj_set_style_text_color(ui_LabelStateONPompa1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStateONPompa1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_LabelStateONPompa1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_LabelStateONPompa1, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_PanelPompa2 = lv_obj_create(ui_screenControlling);
lv_obj_set_width( ui_PanelPompa2, 123);
lv_obj_set_height( ui_PanelPompa2, 131);
lv_obj_set_x( ui_PanelPompa2, -90 );
lv_obj_set_y( ui_PanelPompa2, -47 );
lv_obj_set_align( ui_PanelPompa2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPompa2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPompa2 = lv_label_create(ui_PanelPompa2);
lv_obj_set_width( ui_LabelPompa2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPompa2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPompa2, 0 );
lv_obj_set_y( ui_LabelPompa2, -40 );
lv_obj_set_align( ui_LabelPompa2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPompa2,"Mixer\nPump");
lv_obj_set_style_text_align(ui_LabelPompa2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonONOFF2 = lv_btn_create(ui_PanelPompa2);
lv_obj_set_width( ui_ButtonONOFF2, 100);
lv_obj_set_height( ui_ButtonONOFF2, 50);
lv_obj_set_x( ui_ButtonONOFF2, 0 );
lv_obj_set_y( ui_ButtonONOFF2, 30 );
lv_obj_set_align( ui_ButtonONOFF2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonONOFF2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonONOFF2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonONOFF2, lv_color_hex(0x0F8161), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonONOFF2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonONOFF2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonONOFF2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonONOFF2, lv_color_hex(0xE20000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ButtonONOFF2, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_color(ui_ButtonONOFF2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_ButtonONOFF2, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelON2 = lv_label_create(ui_ButtonONOFF2);
lv_obj_set_width( ui_LabelON2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelON2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelON2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelON2,"ON");
lv_obj_set_style_text_color(ui_LabelON2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_LabelON2, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelOFF2 = lv_label_create(ui_ButtonONOFF2);
lv_obj_set_width( ui_LabelOFF2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelOFF2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelOFF2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelOFF2,"OFF");
lv_obj_set_style_text_color(ui_LabelOFF2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelOFF2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_LabelOFF2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_LabelOFF2, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelStateOFFPompa2 = lv_label_create(ui_PanelPompa2);
lv_obj_set_width( ui_LabelStateOFFPompa2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStateOFFPompa2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStateOFFPompa2, 0 );
lv_obj_set_y( ui_LabelStateOFFPompa2, -15 );
lv_obj_set_align( ui_LabelStateOFFPompa2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStateOFFPompa2,"State: OFF");
lv_obj_set_style_text_color(ui_LabelStateOFFPompa2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStateOFFPompa2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_LabelStateOFFPompa2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_LabelStateOFFPompa2, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelStateONPompa2 = lv_label_create(ui_PanelPompa2);
lv_obj_set_width( ui_LabelStateONPompa2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStateONPompa2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStateONPompa2, 0 );
lv_obj_set_y( ui_LabelStateONPompa2, -15 );
lv_obj_set_align( ui_LabelStateONPompa2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStateONPompa2,"State: ON");
lv_obj_set_style_text_color(ui_LabelStateONPompa2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStateONPompa2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_LabelStateONPompa2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_LabelStateONPompa2, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_PanelPompa3 = lv_obj_create(ui_screenControlling);
lv_obj_set_width( ui_PanelPompa3, 123);
lv_obj_set_height( ui_PanelPompa3, 131);
lv_obj_set_x( ui_PanelPompa3, 90 );
lv_obj_set_y( ui_PanelPompa3, -47 );
lv_obj_set_align( ui_PanelPompa3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPompa3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPompa3 = lv_label_create(ui_PanelPompa3);
lv_obj_set_width( ui_LabelPompa3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPompa3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPompa3, 0 );
lv_obj_set_y( ui_LabelPompa3, -40 );
lv_obj_set_align( ui_LabelPompa3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPompa3,"Dosing\nPump");
lv_obj_set_style_text_align(ui_LabelPompa3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonONOFF3 = lv_btn_create(ui_PanelPompa3);
lv_obj_set_width( ui_ButtonONOFF3, 100);
lv_obj_set_height( ui_ButtonONOFF3, 50);
lv_obj_set_x( ui_ButtonONOFF3, 0 );
lv_obj_set_y( ui_ButtonONOFF3, 30 );
lv_obj_set_align( ui_ButtonONOFF3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonONOFF3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonONOFF3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonONOFF3, lv_color_hex(0x0F8161), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonONOFF3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonONOFF3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonONOFF3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonONOFF3, lv_color_hex(0xE20000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ButtonONOFF3, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_color(ui_ButtonONOFF3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_ButtonONOFF3, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelON3 = lv_label_create(ui_ButtonONOFF3);
lv_obj_set_width( ui_LabelON3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelON3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelON3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelON3,"ON");
lv_obj_set_style_text_color(ui_LabelON3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_LabelON3, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelOFF3 = lv_label_create(ui_ButtonONOFF3);
lv_obj_set_width( ui_LabelOFF3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelOFF3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelOFF3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelOFF3,"OFF");
lv_obj_set_style_text_color(ui_LabelOFF3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelOFF3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_LabelOFF3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_LabelOFF3, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelStateOFFPompa3 = lv_label_create(ui_PanelPompa3);
lv_obj_set_width( ui_LabelStateOFFPompa3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStateOFFPompa3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStateOFFPompa3, 0 );
lv_obj_set_y( ui_LabelStateOFFPompa3, -15 );
lv_obj_set_align( ui_LabelStateOFFPompa3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStateOFFPompa3,"State: OFF");
lv_obj_set_style_text_color(ui_LabelStateOFFPompa3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStateOFFPompa3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_LabelStateOFFPompa3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_LabelStateOFFPompa3, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelStateONPompa3 = lv_label_create(ui_PanelPompa3);
lv_obj_set_width( ui_LabelStateONPompa3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStateONPompa3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStateONPompa3, 0 );
lv_obj_set_y( ui_LabelStateONPompa3, -15 );
lv_obj_set_align( ui_LabelStateONPompa3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStateONPompa3,"State: ON");
lv_obj_set_style_text_color(ui_LabelStateONPompa3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStateONPompa3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_LabelStateONPompa3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_LabelStateONPompa3, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_PanelExh = lv_obj_create(ui_screenControlling);
lv_obj_set_width( ui_PanelExh, 123);
lv_obj_set_height( ui_PanelExh, 131);
lv_obj_set_x( ui_PanelExh, 280 );
lv_obj_set_y( ui_PanelExh, -47 );
lv_obj_set_align( ui_PanelExh, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelExh, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelExh = lv_label_create(ui_PanelExh);
lv_obj_set_width( ui_LabelExh, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelExh, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelExh, 0 );
lv_obj_set_y( ui_LabelExh, -40 );
lv_obj_set_align( ui_LabelExh, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelExh,"Exhaust\nFan");
lv_obj_set_style_text_align(ui_LabelExh, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonONOFF4 = lv_btn_create(ui_PanelExh);
lv_obj_set_width( ui_ButtonONOFF4, 100);
lv_obj_set_height( ui_ButtonONOFF4, 50);
lv_obj_set_x( ui_ButtonONOFF4, 0 );
lv_obj_set_y( ui_ButtonONOFF4, 30 );
lv_obj_set_align( ui_ButtonONOFF4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonONOFF4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonONOFF4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonONOFF4, lv_color_hex(0x0F8161), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonONOFF4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonONOFF4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonONOFF4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonONOFF4, lv_color_hex(0xE20000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ButtonONOFF4, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_color(ui_ButtonONOFF4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_ButtonONOFF4, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelON4 = lv_label_create(ui_ButtonONOFF4);
lv_obj_set_width( ui_LabelON4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelON4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelON4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelON4,"ON");
lv_obj_set_style_text_color(ui_LabelON4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_LabelON4, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelOFF4 = lv_label_create(ui_ButtonONOFF4);
lv_obj_set_width( ui_LabelOFF4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelOFF4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelOFF4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelOFF4,"OFF");
lv_obj_set_style_text_color(ui_LabelOFF4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelOFF4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_LabelOFF4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_LabelOFF4, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelStateOFFExh = lv_label_create(ui_PanelExh);
lv_obj_set_width( ui_LabelStateOFFExh, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStateOFFExh, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStateOFFExh, 0 );
lv_obj_set_y( ui_LabelStateOFFExh, -15 );
lv_obj_set_align( ui_LabelStateOFFExh, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStateOFFExh,"State: OFF");
lv_obj_set_style_text_color(ui_LabelStateOFFExh, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStateOFFExh, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_LabelStateOFFExh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_LabelStateOFFExh, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LabelStateONExh = lv_label_create(ui_PanelExh);
lv_obj_set_width( ui_LabelStateONExh, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStateONExh, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStateONExh, 0 );
lv_obj_set_y( ui_LabelStateONExh, -15 );
lv_obj_set_align( ui_LabelStateONExh, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStateONExh,"State: ON");
lv_obj_set_style_text_color(ui_LabelStateONExh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStateONExh, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_LabelStateONExh, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_LabelStateONExh, 255, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_add_event_cb(ui_ButtonNutrient2, ui_event_ButtonNutrient2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonHome2, ui_event_ButtonHome2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonONOFF1, ui_event_ButtonONOFF1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonONOFF2, ui_event_ButtonONOFF2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonONOFF3, ui_event_ButtonONOFF3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonONOFF4, ui_event_ButtonONOFF4, LV_EVENT_ALL, NULL);

}
